name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest  # Ensure the runner uses Windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up ChromeDriver
        run: |
          choco install chromedriver --version=113.0.5672.63  # Install ChromeDriver via Chocolatey
          refreshenv  # Refresh environment variables

      - name: Run Streamlit app
        run: |
          streamlit run streamlit_app.py
